:sparkles: pipeline

diff --git a/.github/workflows/monitoring.yml b/.github/workflows/monitoring.yml
--- a/.github/workflows/monitoring.yml
+++ b/.github/workflows/monitoring.yml
@@ -46,13 +46,12 @@ jobs:
             SIZE=$(stat --format=%s "$FILE")
             echo "size=$SIZE" >> $GITHUB_ENV
           else
-            echo "File not found: $FILE"
+            echo "Error: File not found: $FILE"
             exit 1
           fi
 
       - name: Get Slack upload URL
         run: |
-          # Usa la variable size que calculaste anteriormente
           response=$(curl -s -X POST \
             -H "Authorization: Bearer ${{ secrets.SLACK_TOKEN_BOTS }}" \
             -H "Content-Type: application/x-www-form-urlencoded; charset=utf-8" \
@@ -62,92 +61,58 @@ jobs:
           
           echo "$response"
           
-          # Extrae la URL de carga de la respuesta
           upload_url=$(echo "$response" | jq -r '.upload_url')
-          
-          # Verifica si se obtuvo correctamente la URL de carga
-          if [ "$upload_url" == "null" ]; then
-            echo "Error fetching upload URL: $response"
+          if [ "$upload_url" == "null" ] || [ -z "$upload_url" ]; then
+            echo "Error: No se pudo obtener la URL de carga de Slack"
             exit 1
           fi
-
-          # Guarda la URL de carga para usarla en los siguientes pasos
           echo "upload_url=$upload_url" >> $GITHUB_ENV
           
-          # Extrae la URL de carga de la respuesta
           file_id=$(echo "$response" | jq -r '.file_id')
-          
-          # Verifica si se obtuvo correctamente la URL de carga
-          if [ "$file_id" == "null" ]; then
-            echo "Error fetching upload URL: $response"
+          if [ "$file_id" == "null" ] || [ -z "$file_id" ]; then
+            echo "Error: No se pudo obtener el ID del archivo"
             exit 1
           fi
-
-          # Guarda la URL de carga para usarla en los siguientes pasos
           echo "file_id=$file_id" >> $GITHUB_ENV
 
       - name: Upload file to Slack
         run: |
-          # Realiza la carga del archivo y guarda la respuesta en una variable
           response_upload=$(curl -s -X POST \
-          -H "Content-Type: text/html" \
-          -H "Cookie: b=13c64025dfc69e83ce80ae4049ba7bb0; utm=%7B%7D; x=13c64025dfc69e83ce80ae4049ba7bb0.1733948334" \
-          --data-binary @target/site/serenity/serenity-summary.html \
-          "${{ env.upload_url }}")
-
-          # Imprime la respuesta para depuración
+            -H "Content-Type: text/html" \
+            --data-binary @target/site/serenity/serenity-summary.html \
+            "${{ env.upload_url }}")
           echo "respuesta: $response_upload"
-          
-          # Extrae el número de la respuesta (51461)
           id=$(echo $response_upload | awk -F ' - ' '{print $2}')
-
-          # Imprime el número extraído
           echo "id: $id"
-          
-          # Guarda la URL de carga para usarla en los siguientes pasos
           echo "id=$id" >> $GITHUB_ENV
 
       - name: Complete Slack upload
         run: |
-          # Realiza la llamada para completar la carga del archivo
           response_url=$(curl -s -X POST \
-          -H "Authorization: Bearer ${{ secrets.SLACK_TOKEN_BOTS }}" \
-          -H "Content-Type: application/json; text/html; charset=utf-8" \
-          -d '{"files":[{"id":"'"${{ env.file_id }}"'"}]}' \
-          https://slack.com/api/files.completeUploadExternal)
-        
-          # Imprime la respuesta para depuración
-          echo "Slack API response: $response_url"
-        
-          # Extrae la URL de carga de la respuesta
+            -H "Authorization: Bearer ${{ secrets.SLACK_TOKEN_BOTS }}" \
+            -H "Content-Type: application/json; charset=utf-8" \
+            -d '{"files":[{"id":"'"${{ env.file_id }}"'"}]}' \
+            https://slack.com/api/files.completeUploadExternal)
+          
           url_private=$(echo "$response_url" | jq -r '.files[0].url_private')
-          
-          # Verifica si se obtuvo correctamente la URL de carga
           if [ "$url_private" == "null" ] || [ -z "$url_private" ]; then
-          echo "Error fetching upload URL: $response_url"
-          exit 1
+            echo "Error: No se pudo obtener la URL de carga completa"
+            exit 1
           fi
-          
-          # Guarda la URL de carga para usarla en los siguientes pasos
           echo "url_private=$url_private" >> $GITHUB_ENV
-          
-          # Imprime la respuesta para depuración
-          echo "URL html: $url_private"
-
 
       - name: Notificar a Slack
         run: |
           if [ "${{ env.tests_failed }}" == "true" ]; then
             curl -X POST -H 'Content-type: application/json' \
-            --data '{"text":":rotating_light:¡Atención equipo!:rotating_light:\n\nParece que algo no anda bien con los widgets/banners :scream:. ¡Se presentó un pequeño fallo! :hammer_and_wrench:\n\n:mag: Revisa por favor para que todo vuelva a la normalidad. ¡Gracias por estar al tanto! :spock-hand:\n\n\n:warning:Revisa el reporte de pruebas aquí: '"${{ env.url_private }}"'. No olvides instalar ModHeader y agregar tu token de Slack.:warning:\n\n\n\n:cat:","channel":"#automatizacion-pruebas-prd"}' \
-            ${{ secrets.SLACK_WEBHOOK_URL }}
+            --data $'{
+              "text": ":rotating_light:¡Atención equipo!:rotating_light:\n\nParece que algo no anda bien con los widgets/banners :scream:. ¡Se presentó un pequeño fallo! :hammer_and_wrench:\n\n:mag: Revisa por favor para que todo vuelva a la normalidad. ¡Gracias por estar al tanto! :spock-hand:\n\n\n\n:warning:Revisa el reporte de pruebas aquí: '${{ env.url_private }}'. No olvides instalar ModHeader y agregar tu token de Slack.:warning:\n\n\n\n:cat:",
+              "channel": "#automatizacion-pruebas-prd"
+            }' ${{ secrets.SLACK_WEBHOOK_URL }}
           else
             curl -X POST -H 'Content-type: application/json' \
-            --data '{"text":":confetti_ball: ¡Éxito total, equipo! :confetti_ball:\n\nLas pruebas realizadas en producción a los aliados salieron de maravilla :sparkles: :muscle:.\n\nTodo está funcionando como debería. ¡Gran trabajo! :tada: Sigamos brillando. :rocket:\n\n\n:warning:Revisa el reporte de pruebas aquí: '"${{ env.url_private }}"'. No olvides instalar ModHeader y agregar tu token de Slack.:warning:\n\n\n\n:cat:","channel":"#automatizacion-pruebas-prd"}' \
-            ${{ secrets.SLACK_WEBHOOK_URL }}
+            --data $'{
+              "text": ":confetti_ball: ¡Éxito total, equipo! :confetti_ball:\n\nLas pruebas realizadas en producción a los aliados salieron de maravilla :sparkles: :muscle:.\n\nTodo está funcionando como debería. ¡Gran trabajo! :tada: Sigamos brillando. :rocket:\n\n\n:warning:Revisa el reporte de pruebas aquí: '${{ env.url_private }}'. No olvides instalar ModHeader y agregar tu token de Slack.:warning:\n\n\n\n:cat:",
+              "channel": "#automatizacion-pruebas-prd"
+            }' ${{ secrets.SLACK_WEBHOOK_URL }}
           fi
-
-
-
-
-
